'use client';

import Link from 'next/link';
import { useState, type ReactNode } from 'react';
import { Activity, ArrowUpRight, BadgeCheck, BookOpen, ChevronDown, ChevronRight, Clock3, Files, FlaskConical, HelpCircle, LayoutDashboard, LockKeyhole, Menu, Plus, ScanLine, ShieldCheck, UserRound, X } from 'lucide-react';
import { AccessibleDialog, Button } from '@/components/ui';
import { terms } from '@/lib/clinicalTerms';

export type View = keyof typeof terms.nav;
const navigation: { id: View; icon: typeof Activity }[] = [{ id: 'overview', icon: LayoutDashboard }, { id: 'labs', icon: FlaskConical }, { id: 'reports', icon: Files }, { id: 'timeline', icon: Clock3 }, { id: 'review', icon: BadgeCheck }, { id: 'summary', icon: BookOpen }, { id: 'intake', icon: UserRound }];
export function AppShell({ children, view, onView, patientName, reviewCount = 0, onUpload }: { children: ReactNode; view?: View; onView?: (view: View) => void; patientName?: string; reviewCount?: number; onUpload?: () => void }) {
  const [mobile, setMobile] = useState(false);
  const [info, setInfo] = useState<'privacy' | 'help' | null>(null);
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a>
    <aside className={`sidebar ${mobile ? 'sidebar-open' : ''}`}><div className="brand-row"><Link href="/" className="brand" aria-label="MedLens home"><span className="brand-mark"><ScanLine size={24} /></span>MedLens<span className="brand-period">.</span></Link><button className="icon-button mobile-close" onClick={() => setMobile(false)} aria-label="Close navigation"><X size={20} /></button></div>
      <div className="workspace-switch"><span className="workspace-icon"><Activity size={18} /></span><span><strong>Clinical workspace</strong><small>Personal workspace</small></span><ChevronDown size={14} /></div>
      <div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(({ id, icon: Icon }) => <button key={id} className={`nav-item ${view === id ? 'nav-active' : ''}`} onClick={() => { if (onView) onView(id); else window.location.assign('/#new-record'); setMobile(false); }}><Icon size={18} /><span>{terms.nav[id]}</span>{id === 'review' && reviewCount > 0 && <span className="nav-count">{reviewCount}</span>}</button>)}</nav>
      <Link className="new-patient" href="/#new-record"><Plus size={17} />New patient record</Link>
      <div className="sidebar-bottom"><div className="privacy-note"><ShieldCheck size={19} /><strong>Evidence comes first.</strong><p>Every extracted detail stays connected to its source.</p></div><button className="nav-item" onClick={() => setInfo('help')}><HelpCircle size={18} />How MedLens works<ArrowUpRight size={14} /></button><button className="nav-item" onClick={() => setInfo('privacy')}><LockKeyhole size={18} />Data & privacy</button><div className="session-account"><div className="account-avatar">LW</div><div><strong>Local workspace</strong><small>Private browser session</small></div><ShieldCheck size={16} /></div></div>
    </aside>{mobile && <button className="mobile-scrim" onClick={() => setMobile(false)} aria-label="Close navigation" />}
    <div className="app-body"><header className="topbar"><button className="icon-button mobile-toggle" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu size={21} /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={13} /><span>{patientName ?? 'Getting started'}</span>{view && <><ChevronRight size={13} /><strong>{terms.nav[view]}</strong></>}</div><div className="topbar-actions"><span className="session-chip"><LockKeyhole size={13} />Session only</span>{onUpload && <Button onClick={onUpload}><Plus size={16} />Upload report</Button>}</div></header><main id="main-content" className="main-content">{children}</main><footer className="app-footer"><ShieldCheck size={14} /><span>{terms.disclaimer}</span><span className="footer-wordmark">MedLens</span></footer></div>
    <AccessibleDialog open={info !== null} onOpenChange={() => setInfo(null)} title={info === 'privacy' ? 'Your data, in this session' : 'From report to a record you can review'} description={info === 'privacy' ? 'Understand how this workspace handles your information.' : 'A short guide to the MedLens workflow.'}><div className="dialog-body prose">{info === 'privacy' ? <><p>Records and extracted report text are held in server memory and scoped to a secure browser session cookie. They are not written to a database or browser local storage.</p><p>The session expires automatically. Restarting the server or moving between server instances can remove the record. Export reviewed information if you need to retain it.</p><p>This build has no user accounts or permanent storage. Uploaded file binaries are discarded after processing. If an AI provider is configured, report content may be sent to that provider for extraction.</p></> : <ol className="help-steps"><li><strong>Create a patient record.</strong> Enter only the details you have. Skipped details stay unknown.</li><li><strong>Add a report.</strong> Paste text or upload a supported PDF or image.</li><li><strong>Check the source.</strong> Open any laboratory result to compare its extracted value with the original report text.</li><li><strong>Review and export.</strong> Correct fields, confirm extractions, answer clarifications, and download the record.</li></ol>}<p className="muted">{terms.disclaimer}</p></div></AccessibleDialog>
  </div>;
}
