'use client';

import { useState, type FormEvent } from 'react';
import { BadgeCheck, Check, FileText, History, Pencil, RotateCcw, ShieldCheck, TriangleAlert, X } from 'lucide-react';
import type { LabResult, MedicalRecord } from '@/lib/schema';
import type { PatchRecord } from '@/lib/client';
import { terms } from '@/lib/clinicalTerms';
import { formatDate } from '@/lib/utils/display';
import { AccessibleDialog, Button, ProvenanceChip, StatusBadge, VerificationBadge } from './ui';

export function EvidencePanel({ lab, record, onClose, patch, busy }: { lab: LabResult | null; record: MedicalRecord; onClose: () => void; patch: PatchRecord; busy: boolean }) {
  const [editing, setEditing] = useState(false); const [rejecting, setRejecting] = useState(false);
  if (!lab) return null;
  const document = record.documents.find(d => d.id === lab.source.sourceDocumentId);
  const fields = [{ name: 'sourceName', label: 'Original report term', value: lab.sourceName }, { name: 'value', label: 'Recorded value', value: lab.value }, { name: 'unit', label: 'Unit', value: lab.unit }, { name: 'referenceRange', label: 'Source range', value: lab.referenceRange }, { name: 'reportDate', label: 'Report date', value: lab.reportDate }];
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!lab) return;
    const data = new FormData(event.currentTarget); const reason = String(data.get('reason') ?? 'Human source review');
    const updates = fields.filter(f => (data.get(f.name) || null) !== f.value).map(f => ({ id: lab.id, field: f.name, value: data.get(f.name) || null, reason }));
    if (!updates.length) { setEditing(false); return; }
    if (await patch({ updates }, 'Extracted details updated')) setEditing(false);
  }
  async function action(action: 'verify' | 'reject' | 'restore' | 'revert' | 'unverify') { if (lab && await patch({ verifications: [{ id: lab.id, action }] }, action === 'verify' ? 'Extraction confirmed' : 'Review decision saved')) setRejecting(false); }
  return <AccessibleDialog open={!!lab} onOpenChange={() => { setEditing(false); setRejecting(false); onClose(); }} title="Review extraction" description="Compare the structured detail with the exact text in the report." wide><div className="evidence-workspace"><section className="source-pane"><div className="source-pane-heading"><FileText size={19} /><div><strong>{document?.fileName ?? 'Pasted report text'}</strong><span>{formatDate(document?.reportDate ?? null)} · {document?.kind === 'TEXT' ? 'Text source' : document?.kind}</span></div></div><div className="source-document"><div className="source-document-meta">SOURCE EVIDENCE{lab.source.evidence?.locator?.line && <span>Line {lab.source.evidence.locator.line}</span>}</div><h3>{document?.issuer ?? 'Original report text'}</h3><p className="source-context">This excerpt is preserved from the report. Review it before confirming the extracted detail.</p><blockquote className="source-excerpt">{lab.source.evidence?.originalText ?? 'Source excerpt is unavailable. Check the full report text below.'}</blockquote><details className="full-source"><summary>View complete extracted source</summary><pre>{document?.extraction.rawText ?? terms.notProvided}</pre></details><div className="source-integrity"><ShieldCheck size={15} /><span>Original text preserved for traceability</span></div></div></section>
      <section className="extraction-pane"><div className="extraction-topline"><span>STRUCTURED EXTRACTION</span><VerificationBadge lab={lab} /></div><h2>{lab.canonicalName ?? lab.sourceName}</h2><p className="original-label">Original report term: <strong>{lab.sourceName}</strong></p><ProvenanceChip source={lab.source} />
      {editing ? <form className="edit-form" onSubmit={save}>{fields.map(field => <label className="field" key={field.name}>{field.label}<input name={field.name} defaultValue={field.value ?? ''} type={field.name === 'reportDate' ? 'date' : 'text'} required={field.name === 'sourceName'} maxLength={field.name === 'sourceName' ? 120 : 200} /></label>)}<label className="field">Reason for correction<input name="reason" required maxLength={500} defaultValue="Checked against source report" /></label><p className="field-hint">A range entered here is labeled as user provided. Only enter a range you can verify.</p><div className="button-row"><Button type="submit" variant="primary" busy={busy}>Save correction</Button><Button type="button" onClick={() => setEditing(false)}>Cancel</Button></div></form> : <><div className="extracted-values"><div><span>Recorded value</span><strong className="numeric">{lab.value ?? '—'} <small>{lab.unit}</small></strong></div><div><span>Source range</span><strong className={lab.referenceRange ? 'numeric' : 'range-unavailable'}>{lab.referenceRange ?? terms.noRange}</strong></div></div><StatusBadge status={lab.status} /><p className="status-reason">{lab.statusReason}</p><dl className="extraction-details"><div><dt>Report date</dt><dd>{formatDate(lab.reportDate, true)}</dd></div><div><dt>{terms.confidenceLabel}</dt><dd>{terms.confidence[lab.source.confidence]}</dd></div><div><dt>Extraction method</dt><dd>{lab.source.evidence?.extractionMethod ?? terms.notProvided}</dd></div>{lab.specimen && <div><dt>Specimen</dt><dd>{lab.specimen}</dd></div>}</dl><p className="confidence-reason">{lab.source.confidenceReason}</p>
      {lab.corrections.length > 0 && <details className="audit-trail"><summary><History size={15} />Correction history <span>{lab.corrections.length}</span></summary>{lab.corrections.map((correction, index) => <div className="audit-item" key={`${correction.at}-${index}`}><strong>{correction.field}</strong><p><s>{String(correction.from ?? 'Not provided')}</s> → {String(correction.to ?? 'Not provided')}</p><small>{formatDate(correction.at, true)} · {correction.reason ?? 'Human review'}</small></div>)}<Button variant="ghost" onClick={() => action('revert')} busy={busy}><RotateCcw size={14} />Revert to original extraction</Button></details>}
      {rejecting ? <div className="reject-confirm" role="alert"><TriangleAlert size={18} /><p>Reject this extraction? It will remain in the audit record and be excluded from summaries and comparisons.</p><div className="button-row"><Button variant="danger" onClick={() => action('reject')} busy={busy}>Reject extraction</Button><Button onClick={() => setRejecting(false)}>Cancel</Button></div></div> : <div className="verification-actions">{lab.rejected ? <Button onClick={() => action('restore')} busy={busy}><RotateCcw size={16} />Restore extraction</Button> : <><Button variant="primary" onClick={() => action(lab.verified ? 'unverify' : 'verify')} busy={busy}>{lab.verified ? <BadgeCheck size={16} /> : <Check size={16} />}{lab.verified ? 'Undo verification' : 'Confirm extraction'}</Button><Button onClick={() => setEditing(true)} disabled={busy}><Pencil size={15} />Edit</Button><Button variant="ghost" className="reject-button" onClick={() => setRejecting(true)} disabled={busy}><X size={15} />Reject</Button></>}</div>}</>}
      </section></div></AccessibleDialog>;
}
