'use client';

import { useState } from 'react';
import { ArrowUpRight, Search, SlidersHorizontal, X } from 'lucide-react';
import type { LabResult, MedicalRecord } from '@/lib/schema';
import { terms } from '@/lib/clinicalTerms';
import { formatDate } from '@/lib/utils/display';
import { Button, EmptyState, ProvenanceChip, StatusBadge, VerificationBadge } from './ui';

export function LabResultsTable({ record, onSelect, compact = false, onViewAll }: { record: MedicalRecord; onSelect: (lab: LabResult) => void; compact?: boolean; onViewAll?: () => void }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [source, setSource] = useState('current');
  const currentIds = new Set(record.documents.filter(d => d.role !== 'PREVIOUS_REPORT').map(d => d.id));
  const rows = record.labResults.filter(lab => (source === 'all' || currentIds.has(lab.source.sourceDocumentId ?? '')) && (!query || `${lab.canonicalName} ${lab.sourceName}`.toLowerCase().includes(query.toLowerCase())) && (filter === 'all' || (filter === 'outside' ? ['ABOVE', 'BELOW'].includes(lab.status) : filter === 'review' ? !lab.verified && !lab.rejected : filter === 'verified' ? lab.verified : lab.status === 'NO_SOURCE_RANGE')));
  const displayed = compact ? rows.slice(0, 6) : rows;
  return <section className="panel labs-panel"><div className="panel-heading"><div><h2>{compact ? 'Recent laboratory results' : 'Laboratory results'}<span className="count-chip">{rows.length}</span></h2>{compact && <p>Recorded values, with the ranges provided by the source.</p>}</div>{compact && <Button variant="ghost" onClick={onViewAll}>View all<ArrowUpRight size={15} /></Button>}</div>
    {!compact && <div className="filter-bar"><label className="search-field"><Search size={16} /><span className="sr-only">Search laboratory results</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tests or original terms…" />{query && <button aria-label="Clear search" onClick={() => setQuery('')}><X size={14} /></button>}</label><label className="filter-select"><SlidersHorizontal size={15} /><span className="sr-only">Filter results</span><select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All statuses</option><option value="outside">{terms.metrics.outside}</option><option value="review">{terms.review}</option><option value="verified">{terms.verified}</option><option value="unavailable">{terms.status.NO_SOURCE_RANGE}</option></select></label><label className="filter-select"><span className="sr-only">Report selection</span><select value={source} onChange={e => setSource(e.target.value)}><option value="current">Current reports</option><option value="all">All reports</option></select></label></div>}
    {displayed.length ? <div className="table-scroll"><table className={`lab-table ${compact ? 'table-compact' : ''}`}><caption className="sr-only">Extracted laboratory values and source reference ranges</caption><thead><tr><th scope="col">Test / parameter</th><th scope="col">Recorded value</th><th scope="col">Source range</th><th scope="col">Status</th>{!compact && <><th scope="col">Date / source</th><th scope="col">Verification</th></>}<th scope="col"><span className="sr-only">Review result</span></th></tr></thead><tbody>{displayed.map(lab => <tr key={lab.id} className={lab.rejected ? 'rejected-row' : ''}><th scope="row"><button className="test-link" onClick={() => onSelect(lab)}>{lab.canonicalName ?? lab.sourceName}</button><span className="original-term">Original report term: {lab.sourceName}</span></th><td className="numeric value-cell">{lab.value ?? '—'}<span className="unit">{lab.unit ?? ''}</span></td><td className={lab.referenceRange ? 'numeric range-cell' : 'range-missing'}>{lab.referenceRange ?? terms.noRange}</td><td><StatusBadge status={lab.status} /></td>{!compact && <><td><span className="date-cell">{formatDate(lab.reportDate, true)}</span><ProvenanceChip source={lab.source} /></td><td><VerificationBadge lab={lab} /></td></>}<td><button className="icon-button result-open" onClick={() => onSelect(lab)} aria-label={`Review ${lab.canonicalName ?? lab.sourceName}`}><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table></div> : <EmptyState title={record.labResults.length ? terms.empty.filtered : terms.empty.labs} action={record.labResults.length ? <Button onClick={() => { setQuery(''); setFilter('all'); setSource('all'); }}>Clear filters</Button> : undefined} />}
    <div className="table-footer"><span>Every value is linked to its source report.</span>{compact ? <span>{displayed.length} of {rows.length} results</span> : <span>{rows.length} result{rows.length !== 1 ? 's' : ''}</span>}</div>
  </section>;
}
