'use client';

import { useCallback, useEffect, useState } from 'react';
import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import { ArrowRight, ArrowUpRight, BadgeCheck, Check, ChevronDown, Download, FileCheck2, FileText, FlaskConical, Info, ListChecks, Plus, ShieldCheck, TriangleAlert } from 'lucide-react';
import { AppShell, type View } from './AppShell';
import { Button, EmptyState, ErrorState, ProvenanceChip, Skeleton } from './ui';
import { LabResultsTable } from './LabResultsTable';
import { EvidencePanel } from './EvidencePanel';
import { UploadDialog } from './UploadDialog';
import { ReviewPanel } from './ReviewPanel';
import { ReportsSection, SummarySection, TimelineSection } from './RecordSections';
import { PatientDetails } from './PatientDetails';
import { jsonOptions, requestRecord, type PatchRecord } from '@/lib/client';
import type { LabResult, MedicalRecord } from '@/lib/schema';
import { terms } from '@/lib/clinicalTerms';
import { formatDate, initials } from '@/lib/utils/display';

const descriptions: Record<View, string> = { overview: 'The information you have. The context you need.', labs: 'Structured measurements, always connected to the source.', reports: 'The source documents behind this patient record.', timeline: 'A source-by-source view of recorded measurements.', review: 'Check the details. Keep the source in sight.', summary: 'A factual overview of the information in this record.', intake: 'Patient-provided context and details from the reports.' };

function ExportMenu({ id }: { id: string }) { return <DropdownMenu.Root><DropdownMenu.Trigger asChild><Button><Download size={16} />Export record<ChevronDown size={14} /></Button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="dropdown-content" align="end" sideOffset={8}><DropdownMenu.Label>Download this record</DropdownMenu.Label>{[{ format: 'md', label: 'Markdown · shareable summary' }, { format: 'csv', label: 'CSV · laboratory results' }, { format: 'json', label: 'JSON · complete record' }].map(item => <DropdownMenu.Item asChild key={item.format}><a href={`/api/record/${id}/export?format=${item.format}`} download><FileText size={16} />{item.label}</a></DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>; }
function Overview({ record, onView, onSelect, onUpload }: { record: MedicalRecord; onView: (view: View) => void; onSelect: (lab: LabResult) => void; onUpload: () => void }) {
  const metrics = [{ label: terms.metrics.reports, value: record.stats.documentsProcessed, icon: FileText, detail: 'Connected source documents' }, { label: terms.metrics.observations, value: record.stats.valuesExtracted, icon: FlaskConical, detail: 'Structured from your reports' }, { label: terms.metrics.outside, value: record.stats.outOfRange, icon: ListChecks, detail: 'Compared with printed ranges' }, { label: terms.metrics.review, value: record.stats.needsReview, icon: BadgeCheck, detail: 'Ready for human verification' }];
  const conflicts = record.conflicts.filter(c => c.status !== 'RESOLVED');
  return <>{conflicts.length > 0 && <div className="review-alert"><div className="alert-icon"><TriangleAlert size={19} /></div><div><strong>{conflicts.length} detail{conflicts.length !== 1 ? 's' : ''} to clarify across this record</strong><p>Some sources contain different information. Review them side by side.</p></div><Button onClick={() => onView('review')}>Review details<ArrowRight size={15} /></Button></div>}
    <div className="metrics-strip">{metrics.map(metric => <div className="metric" key={metric.label}><div className="metric-top"><span>{metric.label}</span><metric.icon size={17} /></div><strong>{metric.value.toString().padStart(2, '0')}</strong><p>{metric.detail}</p></div>)}</div>
    {!record.documents.length ? <section className="panel first-upload"><EmptyState title="Bring the first report into focus." action={<Button variant="primary" onClick={onUpload}><Plus size={16} />Upload report</Button>}>Add a medical report to start building a structured, traceable record.</EmptyState></section> : <div className="overview-grid"><div className="overview-main"><LabResultsTable record={record} onSelect={onSelect} compact onViewAll={() => onView('labs')} /><ReportsSection record={record} upload={onUpload} compact /><SummarySection record={record} compact /></div><aside className="overview-aside"><section className="panel review-progress"><div className="panel-heading"><h2>Record verification</h2><ShieldCheck size={18} /></div><div className="progress-content"><div className="progress-numbers"><strong>{Math.round(record.stats.verifiedPercent)}<small>%</small></strong><span>human verified</span></div><progress value={record.stats.verifiedPercent} max={100} aria-label="Human verification progress" /><p>{record.stats.verified} of {record.stats.labResults} laboratory results confirmed</p><Button onClick={() => onView('review')}>Continue review<ArrowRight size={15} /></Button><div className="review-tip"><Info size={15} /><span>Verification confirms the extraction matches the source.</span></div></div></section>
    <section className="panel attention-panel"><div className="panel-heading"><h2>A closer look</h2><ListChecks size={18} /></div><div className="attention-list">{conflicts.slice(0, 2).map(conflict => <button key={conflict.id} onClick={() => onView('review')}><span className="attention-icon"><TriangleAlert size={16} /></span><div><strong>{conflict.title}</strong><p>Compare source information</p></div><ChevronDown size={15} className="rotate-left" /></button>)}{record.labResults.filter(l => l.status === 'NO_SOURCE_RANGE' && !l.rejected).slice(0, 1).map(lab => <button key={lab.id} onClick={() => onSelect(lab)}><span className="attention-icon neutral"><FileText size={16} /></span><div><strong>{lab.canonicalName ?? lab.sourceName}</strong><p>{terms.status.NO_SOURCE_RANGE}</p></div><ArrowUpRight size={15} /></button>)}{!conflicts.length && !record.labResults.some(l => l.status === 'NO_SOURCE_RANGE') && <p className="empty-inline">No conflicting details found.</p>}</div></section>
    <div className="source-principle"><span><FileCheck2 size={19} /></span><h3>Source before summary.</h3><p>Open any result to see exactly where it came from. You stay in control of the record.</p></div></aside></div>}</>;
}
export function RecordWorkspace({ id }: { id: string }) {
  const [record, setRecord] = useState<MedicalRecord | null>(null); const [view, setView] = useState<View>('overview');
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [upload, setUpload] = useState(false); const [selectedId, setSelectedId] = useState<string | null>(null); const [toast, setToast] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const next = await requestRecord(`/api/record/${id}`); setRecord(next); const search = new URLSearchParams(window.location.search); const page = search.get('view'); if (page && page in terms.nav) setView(page as View); if (search.get('upload') === 'true') setUpload(true); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load this record.'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); }, [toast]);
  function navigate(next: View) { setView(next); window.history.replaceState(null, '', `/record/${id}${next === 'overview' ? '' : `?view=${next}`}`); window.scrollTo({ top: 0, behavior: 'instant' }); }
  const patch: PatchRecord = async (body, message = 'Record updated') => { setBusy(true); setError(''); try { const next = await requestRecord(`/api/record/${id}`, jsonOptions(body, 'PATCH')); setRecord(next); setToast(message); return true; } catch (e) { setError(e instanceof Error ? e.message : 'Could not save this change.'); return false; } finally { setBusy(false); } };
  async function regenerate() { setBusy(true); setError(''); try { setRecord(await requestRecord(`/api/record/${id}/summary`, jsonOptions({ regenerate: true }))); setToast('Summary refreshed'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not refresh summary.'); } finally { setBusy(false); } }
  const selected = record?.labResults.find(lab => lab.id === selectedId) ?? null;
  const select = (lab: LabResult) => setSelectedId(lab.id);
  return <AppShell view={record ? view : undefined} onView={record ? navigate : undefined} patientName={record?.patient.nameOrIdentifier} reviewCount={record?.stats.openConflicts} onUpload={record ? () => setUpload(true) : undefined}>{loading ? <Skeleton /> : !record ? <ErrorState message={error || 'This record is no longer available in the current session.'} onRetry={load} /> : <>{record.isDemo && <div className="demo-banner"><FlaskConical size={15} /><span><strong>{terms.demo}</strong> · Explore the workflow with sample patient information.</span><a href="/#new-record">Start your own record<ArrowUpRight size={13} /></a></div>}<div className="page-header"><div><h1>{terms.nav[view] === 'Overview' ? 'Patient overview' : terms.nav[view]}</h1><p>{descriptions[view]}</p></div><ExportMenu id={id} /></div>
      <div className="patient-header"><div className="patient-avatar">{initials(record.patient.nameOrIdentifier)}</div><div className="patient-identity"><h2>{record.patient.nameOrIdentifier}</h2><div><span>{record.patient.age !== null ? `${record.patient.age} years` : 'Age not provided'}</span><i /> <span>{record.patient.sex ? record.patient.sex.toLowerCase().replaceAll('_', ' ') : 'Sex not provided'}</span><i /><ProvenanceChip source={record.patient.source} /></div></div><div className="record-updated"><span>Record updated</span><strong>{formatDate(record.updatedAt, true)}</strong></div><Button variant="ghost" onClick={() => navigate('intake')}>Patient details<ArrowUpRight size={15} /></Button></div>
      {error && <ErrorState message={error} />}{view === 'overview' && <Overview record={record} onView={navigate} onSelect={select} onUpload={() => setUpload(true)} />}{view === 'labs' && <LabResultsTable record={record} onSelect={select} />}{view === 'reports' && <ReportsSection record={record} upload={() => setUpload(true)} />}{view === 'review' && <ReviewPanel record={record} patch={patch} busy={busy} onSelect={select} />}{view === 'timeline' && <TimelineSection record={record} onSelect={select} />}{view === 'summary' && <SummarySection record={record} regenerate={regenerate} busy={busy} />}{view === 'intake' && <PatientDetails record={record} patch={patch} busy={busy} />}
      <UploadDialog record={record} open={upload} onClose={() => setUpload(false)} onRecord={next => { setRecord(next); setToast('Report uploaded'); navigate('labs'); }} /><EvidencePanel key={selectedId} lab={selected} record={record} onClose={() => setSelectedId(null)} patch={patch} busy={busy} />{toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}</>}</AppShell>;
}
