'use client';

import { useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUp, BookOpen, Check, ChevronRight, Clock3, FileText, Minus, Plus, RotateCcw, ShieldCheck } from 'lucide-react';
import type { MedicalRecord, SourceDocument, LabResult } from '@/lib/schema';
import { terms } from '@/lib/clinicalTerms';
import { formatBytes, formatDate } from '@/lib/utils/display';
import { AccessibleDialog, Button, EmptyState, ProvenanceChip, StatusBadge } from './ui';

export function SummarySection({ record, regenerate, busy, compact = false }: { record: MedicalRecord; regenerate?: () => void; busy?: boolean; compact?: boolean }) {
  return <section className={`panel summary-panel ${compact ? 'summary-compact' : ''}`}><div className="panel-heading"><div><h2><BookOpen size={19} />{terms.summary}</h2><p>A factual overview of the available record.</p></div><span className="neutral-chip">{record.summary?.generator === 'AI' ? terms.provenance.ai : terms.template}</span></div>{record.summary ? <div className="summary-content"><p>{record.summary.text}</p><ul>{record.summary.bullets.slice(0, compact ? 3 : undefined).map((bullet, i) => <li key={i}>{bullet}</li>)}</ul>{!compact && regenerate && <Button onClick={regenerate} busy={busy}><RotateCcw size={15} />Refresh summary</Button>}<div className="summary-disclaimer"><ShieldCheck size={15} /><p>{terms.disclaimer}</p></div></div> : <EmptyState title={terms.empty.summary} />}</section>;
}
export function ReportsSection({ record, upload, compact = false }: { record: MedicalRecord; upload: () => void; compact?: boolean }) {
  const [selected, setSelected] = useState<SourceDocument | null>(null);
  return <><section className="panel"><div className="panel-heading"><div><h2>Source reports<span className="count-chip">{record.documents.length}</span></h2>{!compact && <p>Original extracted text and processing details.</p>}</div><Button variant="ghost" onClick={upload}><Plus size={15} />Add report</Button></div>{record.documents.length ? <div className="report-list">{record.documents.map(document => <button className="report-item" key={document.id} onClick={() => setSelected(document)}><span className="file-icon"><FileText size={21} /><small>{document.kind}</small></span><div><strong>{document.fileName ?? 'Pasted medical report'}</strong><p>{formatDate(document.reportDate, true)}<span>·</span>{formatBytes(document.sizeBytes)}<span>·</span>{document.role === 'PREVIOUS_REPORT' ? 'Previous report' : 'Current report'}</p><span className="provenance"><Check size={12} />{document.extraction.status === 'OK' ? 'Processed' : 'Partial extraction'}</span></div><ChevronRight size={17} /></button>)}</div> : <EmptyState title={terms.empty.reports} action={<Button onClick={upload}>Upload report</Button>}>Upload a medical report to begin building this patient’s structured record.</EmptyState>}</section>
    {!compact && record.pipeline.length > 0 && <section className="panel pipeline-panel"><div className="panel-heading"><div><h2>Processing activity</h2><p>Actual steps and timings from the most recent report.</p></div><Clock3 size={18} /></div><ol className="pipeline-list">{record.pipeline.map(stage => <li key={stage.id}><span className={`pipeline-icon pipeline-${stage.status.toLowerCase()}`}>{stage.status === 'DONE' ? <Check size={14} /> : <Minus size={14} />}</span><div><strong>{stage.label}</strong>{stage.detail && <p>{stage.detail}</p>}</div><span className="numeric">{stage.status === 'SKIPPED' ? 'Skipped' : stage.durationMs !== null ? `${stage.durationMs.toFixed(0)} ms` : stage.status}</span></li>)}</ol></section>}
    <AccessibleDialog open={!!selected} onOpenChange={() => setSelected(null)} title={selected?.fileName ?? 'Report source'} description="The extracted text is preserved as evidence. Uploaded file binaries are not retained."><div className="dialog-body">{selected?.extraction.warnings.map(warning => <p className="source-warning" key={warning}>{warning}</p>)}<pre className="full-report-text">{selected?.extraction.rawText}</pre></div></AccessibleDialog></>;
}
export function TimelineSection({ record, onSelect }: { record: MedicalRecord; onSelect: (lab: LabResult) => void }) {
  return <div className="timeline-layout"><section className="panel"><div className="panel-heading"><div><h2>Measurements over time</h2><p>Recorded changes between reports. Each source keeps its own reference range.</p></div></div>{record.comparison?.available ? <div className="table-scroll"><table className="comparison-table"><caption className="sr-only">Comparison of recorded measurements between source reports</caption><thead><tr><th scope="col">Test / parameter</th><th scope="col">Previous report</th><th scope="col">Current report</th><th scope="col">Recorded change</th></tr></thead><tbody>{record.comparison.rows.map(row => <tr key={row.canonicalId}><th scope="row">{row.label}<ProvenanceChip source={row.provenance} /></th><td><strong className="numeric">{row.previous ? `${row.previous.value} ${row.previous.unit ?? ''}` : 'Not in report'}</strong><small>{formatDate(row.previous?.date ?? null, true)}</small></td><td><strong className="numeric">{row.current ? `${row.current.value} ${row.current.unit ?? ''}` : 'Not in report'}</strong><small>{formatDate(row.current?.date ?? null, true)}</small></td><td>{row.comparable && row.change?.absolute !== null && row.change ? <span className="change-value numeric">{row.change.direction === 'UP' ? <ArrowUp size={15} /> : row.change.direction === 'DOWN' ? <ArrowDown size={15} /> : <Minus size={15} />}{Math.abs(row.change.absolute).toFixed(2).replace(/\.?0+$/, '') || '0'} {row.current?.unit}</span> : <span className="comparison-reason">{row.incomparableReason ?? 'Not comparable'}</span>}</td></tr>)}</tbody></table></div> : <EmptyState title={terms.empty.timeline}>{record.comparison?.reason}</EmptyState>}</section>
    <section className="panel"><div className="panel-heading"><h2>Report history</h2></div><div className="timeline-list">{[...record.documents].sort((a, b) => (b.reportDate ?? '').localeCompare(a.reportDate ?? '')).map(document => <div className="timeline-event" key={document.id}><div className="timeline-marker"><FileText size={16} /></div><div><span className="event-date">{formatDate(document.reportDate)}</span><h3>{document.fileName ?? 'Pasted report'}</h3>{record.labResults.filter(lab => !lab.rejected && lab.source.sourceDocumentId === document.id).slice(0, 3).map(lab => <button className="timeline-lab" key={lab.id} onClick={() => onSelect(lab)}><span>{lab.canonicalName ?? lab.sourceName}</span><strong className="numeric">{lab.value} {lab.unit}</strong><StatusBadge status={lab.status} /><ArrowRight size={14} /></button>)}</div></div>)}</div></section></div>;
}
