'use client';

import { useState } from 'react';
import { ArrowRight, BadgeCheck, Check, MessageSquareText, TriangleAlert } from 'lucide-react';
import type { Conflict, MedicalRecord, LabResult } from '@/lib/schema';
import type { PatchRecord } from '@/lib/client';
import { terms } from '@/lib/clinicalTerms';
import { Button, EmptyState, ProvenanceChip, VerificationBadge } from './ui';

function ConflictCard({ conflict, patch, busy }: { conflict: Conflict; patch: PatchRecord; busy: boolean }) {
  const [expanded, setExpanded] = useState(false); const [note, setNote] = useState('');
  return <article className={`conflict-card ${conflict.status === 'RESOLVED' ? 'conflict-resolved' : ''}`}><div className="conflict-title">{conflict.status === 'RESOLVED' ? <Check size={17} /> : <TriangleAlert size={17} />}<h3>{conflict.title}</h3><span className="text-label">{conflict.status === 'RESOLVED' ? 'Resolved' : conflict.status === 'ACKNOWLEDGED' ? 'Acknowledged' : 'Review required'}</span></div><p>{conflict.description}</p><div className="conflict-evidence">{conflict.evidence.map((e, i) => <div key={i}><span>{e.label}</span><q>{e.quote}</q></div>)}</div>{conflict.resolutionNote && <p className="resolution-note">Review note: {conflict.resolutionNote}</p>}{conflict.status !== 'RESOLVED' && (expanded ? <div className="conflict-resolution"><label className="field">Your review note<textarea value={note} onChange={e => setNote(e.target.value)} maxLength={2000} rows={2} placeholder="Explain what you checked and how the record should be read" /></label><div className="button-row"><Button variant="primary" busy={busy} disabled={!note.trim()} onClick={() => patch({ resolutions: [{ id: conflict.id, status: 'RESOLVED', note }] }, 'Conflict resolution saved')}>Save resolution</Button><Button disabled={busy || !note.trim()} onClick={() => patch({ resolutions: [{ id: conflict.id, status: 'ACKNOWLEDGED', note }] }, 'Conflict acknowledged')}>Acknowledge</Button><Button variant="ghost" onClick={() => setExpanded(false)}>Cancel</Button></div></div> : <Button variant="ghost" onClick={() => setExpanded(true)}>Review conflict<ArrowRight size={14} /></Button>)}</article>;
}
function ClarificationCard({ record, patch, busy }: { record: MedicalRecord; patch: PatchRecord; busy: boolean }) {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  return <section className="panel clarification-panel"><div className="panel-heading"><h2><MessageSquareText size={18} />{terms.clarify}</h2></div><div className="clarification-list">{record.clarifications.map(question => <div className="clarification-item" key={question.id}><label className="field" htmlFor={question.id}>{question.question}<span className="field-hint">{question.rationale}</span></label>{question.answer ? <div className="answered"><Check size={15} /><span>{question.answer}</span><span className="provenance">{terms.provenance.user}</span></div> : <div className="answer-input"><input id={question.id} value={answers[question.id] ?? ''} maxLength={2000} onChange={e => setAnswers(previous => ({ ...previous, [question.id]: e.target.value }))} placeholder="Add what you know" /><Button disabled={busy || !answers[question.id]?.trim()} onClick={() => patch({ clarificationAnswers: [{ id: question.id, answer: answers[question.id] }] }, 'Clarification saved')}>Save answer</Button></div>}</div>)}</div></section>;
}
export function ReviewPanel({ record, patch, busy, onSelect }: { record: MedicalRecord; patch: PatchRecord; busy: boolean; onSelect: (lab: LabResult) => void }) {
  const queue = record.labResults.filter(lab => !lab.verified && !lab.rejected).sort((a, b) => ({ UNCERTAIN: 0, REVIEW_SUGGESTED: 1, HIGH: 2 }[a.source.confidence] - { UNCERTAIN: 0, REVIEW_SUGGESTED: 1, HIGH: 2 }[b.source.confidence]));
  return <div className="review-layout"><div className="review-main">{record.conflicts.length > 0 && <section className="panel"><div className="panel-heading"><div><h2>{terms.conflict}<span className="count-chip">{record.stats.openConflicts}</span></h2><p>Both sources are preserved. Your review provides the context.</p></div></div><div className="conflicts-list">{record.conflicts.map(conflict => <ConflictCard key={conflict.id} conflict={conflict} patch={patch} busy={busy} />)}</div></section>}
    <section className="panel"><div className="panel-heading"><h2><BadgeCheck size={18} />Extraction review queue<span className="count-chip">{queue.length}</span></h2></div>{queue.length ? <div className="review-queue">{queue.map(lab => <button key={lab.id} className="review-queue-item" onClick={() => onSelect(lab)}><div><strong>{lab.canonicalName ?? lab.sourceName}</strong><ProvenanceChip source={lab.source} /></div><span className="numeric">{lab.value} {lab.unit}</span><VerificationBadge lab={lab} /><ArrowRight size={16} /></button>)}</div> : <EmptyState title={terms.empty.review} />}</section></div><div className="review-aside">{record.clarifications.length > 0 && <ClarificationCard record={record} patch={patch} busy={busy} />}{record.missingInfo.length > 0 && <section className="panel"><div className="panel-heading"><h2>Missing context<span className="count-chip">{record.missingInfo.length}</span></h2></div><ul className="missing-list">{record.missingInfo.map(item => <li key={item.id}><TriangleAlert size={15} /><div><strong>{item.field}</strong><p>{item.why}</p>{item.factId && record.labResults.some(l => l.id === item.factId) && <button className="text-button" onClick={() => { const lab = record.labResults.find(l => l.id === item.factId); if (lab) onSelect(lab); }}>Review source<ArrowRight size={13} /></button>}</div></li>)}</ul></section>}</div></div>;
}
