export interface LabConcept { id: string; name: string; aliases: string[] }
const seed: [string, string, string][] = [
  ["hemoglobin", "Hemoglobin", "hb|hgb|haemoglobin|hemoglobine|hgb whole blood"],
  ["hematocrit", "Hematocrit", "hct|pcv|packed cell volume"],
  ["rbc", "Red blood cell count", "rbc|red blood cells|erythrocyte count"],
  ["wbc", "White blood cell count", "wbc|total leukocyte count|tlc|leukocytes|white blood cells"],
  ["platelets", "Platelets", "plt|platelet count|thrombocytes"],
  ["cbc", "Complete blood count", "cbc|hemogram"],
  ["neutrophils", "Neutrophils", "neutrophil|neutrophil %|segs|polymorphs"],
  ["lymphocytes", "Lymphocytes", "lymphocyte|lymphocyte %"],
  ["monocytes", "Monocytes", "monocyte|monocyte %"],
  ["eosinophils", "Eosinophils", "eosinophil|eosinophil %"],
  ["basophils", "Basophils", "basophil|basophil %"],
  ["esr", "Erythrocyte sedimentation rate", "esr|sed rate"],
  ["crp", "C-reactive protein", "crp|hs-crp|high sensitivity crp"],
  ["glucose_fasting", "Fasting glucose", "fasting blood sugar|fbs|fasting plasma glucose|glucose fasting"],
  ["glucose_random", "Random glucose", "rbs|random blood sugar|glucose random"],
  ["glucose", "Glucose", "blood glucose|blood sugar"],
  ["hba1c", "HbA1c", "glycated hemoglobin|a1c|glycohemoglobin|haemoglobin a1c"],
  ["urea", "Urea", "blood urea"], ["bun", "Blood urea nitrogen", "bun"],
  ["creatinine", "Creatinine", "scr|serum creatinine"], ["uric_acid", "Uric acid", "urate"],
  ["egfr", "Estimated GFR", "egfr|estimated glomerular filtration rate"],
  ["alt", "ALT", "sgpt|alanine aminotransferase|alanine transaminase"],
  ["ast", "AST", "sgot|aspartate aminotransferase|aspartate transaminase"],
  ["alp", "Alkaline phosphatase", "alp"], ["ggt", "GGT", "gamma glutamyl transferase|gamma gt"],
  ["bilirubin_total", "Total bilirubin", "bilirubin total|t bilirubin"],
  ["bilirubin_direct", "Direct bilirubin", "bilirubin direct|conjugated bilirubin"],
  ["bilirubin_indirect", "Indirect bilirubin", "bilirubin indirect|unconjugated bilirubin"],
  ["albumin", "Albumin", "alb"], ["total_protein", "Total protein", "protein total"],
  ["globulin", "Globulin", "globulins"], ["a_g_ratio", "Albumin/globulin ratio", "a/g ratio|ag ratio|albumin globulin ratio"],
  ["tsh", "TSH", "thyroid stimulating hormone|thyrotropin"],
  ["free_t3", "Free T3", "ft3|t3 free"], ["free_t4", "Free T4", "ft4|t4 free"],
  ["total_t3", "Total T3", "tt3|t3 total"], ["total_t4", "Total T4", "tt4|t4 total"],
  ["ldl", "LDL cholesterol", "ldl|ldl-c"], ["hdl", "HDL cholesterol", "hdl|hdl-c"],
  ["vldl", "VLDL cholesterol", "vldl|vldl-c"], ["triglycerides", "Triglycerides", "tg|triglyceride"],
  ["total_cholesterol", "Total cholesterol", "cholesterol total|cholesterol|tc"],
  ["cholesterol_hdl_ratio", "Cholesterol/HDL ratio", "chol hdl ratio|tc hdl ratio|cholesterol hdl ratio"],
  ["sodium", "Sodium", "na|na+"], ["potassium", "Potassium", "k|k+"],
  ["chloride", "Chloride", "cl|cl-"], ["bicarbonate", "Bicarbonate", "hco3|hco3-"],
  ["calcium", "Calcium", "total calcium|ca"], ["ionized_calcium", "Ionized calcium", "ionised calcium|ica"],
  ["magnesium", "Magnesium", "mg"], ["phosphate", "Phosphate", "inorganic phosphorus|phosphorus"],
  ["iron_serum", "Serum iron", "iron|iron serum"], ["tibc", "Total iron binding capacity", "tibc"],
  ["uibc", "Unsaturated iron binding capacity", "uibc"],
  ["transferrin_saturation", "Transferrin saturation", "tsat|iron saturation"],
  ["ferritin", "Ferritin", "serum ferritin"], ["vitamin_b12", "Vitamin B12", "cobalamin|b12|vit b12"],
  ["vitamin_d", "Vitamin D", "25-hydroxy vitamin d|25-oh d|25 oh vitamin d|vit d|vitamin d 25 hydroxy"],
  ["pt_inr", "INR", "pt inr|international normalized ratio"],
  ["prothrombin_time", "Prothrombin time", "pt"],
  ["aptt", "APTT", "activated partial thromboplastin time|ptt"],
  ["hbsag", "HBsAg", "hepatitis b surface antigen"],
  ["anti_hcv", "Anti-HCV", "hcv antibody|hepatitis c antibody"], ["hiv", "HIV", "hiv antibody"],
  ["dengue_ns1", "Dengue NS1", "ns1 antigen|dengue ns1 antigen"],
  ["d_dimer", "D-dimer", "d dimer|ddimer"], ["urine_ph", "Urine pH", "ph urine"],
  ["urine_specific_gravity", "Urine specific gravity", "specific gravity|urine sg"],
  ["urine_protein", "Urine protein", "protein urine"], ["urine_glucose", "Urine glucose", "glucose urine"],
  ["hbsag_quantitative", "HBsAg quantitative", "quantitative hbsag"],
  ["widal", "Widal", "widal test"], ["differential_count", "Differential count", "dlc|differential leukocyte count"],
  ["mcv", "Mean corpuscular volume", "mcv"], ["mch", "Mean corpuscular hemoglobin", "mch"],
  ["mchc", "Mean corpuscular hemoglobin concentration", "mchc"], ["rdw", "Red cell distribution width", "rdw|rdw cv"],
];
export const LAB_CONCEPTS: readonly LabConcept[] = seed.map(([id, name, aliases]) => ({ id, name, aliases: [id.replaceAll("_", " "), name, ...aliases.split("|")] }));
